window.QUESTION_BANK = [
  {
    "id": "1.1-linear-01",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\(3x_1-\\sqrt{2}x_2+7=0\\) is a linear equation in \\(x_1,x_2\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A constant term on the left makes an equation nonlinear.",
    "explanation": "Rewrite it as \\(3x_1-\\sqrt{2}x_2=-7\\). The variables occur only to the first power and are multiplied by constant coefficients.",
    "why": {
      "prompt": "Why is the statement true?",
      "choices": [
        "Because every equation involving two variables is linear.",
        "Because it can be rewritten as \\(a_1x_1+a_2x_2=b\\) with constant coefficients.",
        "Because the number \\(7\\) is positive.",
        "Because a linear equation must have \\(b=0\\)."
      ],
      "correct": 1
    }
  },
  {
    "id": "1.1-linear-02",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\(x_1x_2+x_3=4\\) is a linear equation in \\(x_1,x_2,x_3\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Any equation made from variables and constants is linear.",
    "explanation": "The product \\(x_1x_2\\) prevents the equation from having the form \\(a_1x_1+\\cdots+a_nx_n=b\\).",
    "counterexample": "The obstruction is the product of variables, not the presence of \\(x_3\\)."
  },
  {
    "id": "1.1-linear-03",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\(x_1^2-5x_2=1\\) is a linear equation in \\(x_1,x_2\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Polynomial equations are automatically linear equations.",
    "explanation": "The term \\(x_1^2\\) is nonlinear. In a linear equation each variable appears only to the first power and is multiplied by a scalar coefficient."
  },
  {
    "id": "1.1-linear-04",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\(0x_1+0x_2=5\\) still has the form of a linear equation, even though it has no solution.",
    "answer": true,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "An equation must have a solution in order to count as linear.",
    "explanation": "The coefficients are allowed to be zero. This equation is simply \\(0=5\\), so it is linear in form but inconsistent as a one-equation system."
  },
  {
    "id": "1.1-system-01",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution",
    "statement": "A solution of a linear system must satisfy every equation in the system simultaneously.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Satisfying any one equation is enough to solve a system.",
    "explanation": "A solution of a system is a choice of values for all variables that makes every equation in the system true."
  },
  {
    "id": "1.1-system-02",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution-set",
    "statement": "The solution set of a system is the collection of all assignments of values to the variables that solve the system.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The solution set is the collection of equations in the system.",
    "explanation": "The equations define the conditions. The solution set consists of the vectors or tuples satisfying all of those conditions."
  },
  {
    "id": "1.1-system-03",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "equivalent-systems",
    "statement": "Two linear systems can look different and still be equivalent.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Equivalent systems must contain the same equations.",
    "explanation": "Equivalence is about having the same solution set, not about having identical equations."
  },
  {
    "id": "1.1-system-04",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "equivalent-systems",
    "statement": "If two systems have the same coefficient matrix, then they are equivalent.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The coefficient matrix alone determines the solution set.",
    "explanation": "The right-hand side matters. For example, \\(x=0\\) and \\(x=1\\) have the same coefficient matrix \\([1]\\) but different solution sets.",
    "counterexample": "\\(x=0\\) versus \\(x=1\\)."
  },
  {
    "id": "1.1-system-05",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution-count",
    "statement": "A linear system with real coefficients can have exactly two distinct solutions.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Linear systems can have any finite number of solutions.",
    "explanation": "If \\(u\\) and \\(v\\) are two distinct solutions of \\(Ax=b\\), then \\(tu+(1-t)v\\) is also a solution for every scalar \\(t\\). Thus two distinct solutions force infinitely many.",
    "why": {
      "prompt": "Which idea best explains why?",
      "choices": [
        "Two distinct solutions generate infinitely many solutions along the affine line joining them.",
        "Every consistent system has a pivot in every column.",
        "Every linear system has at least three equations.",
        "A system with two solutions must have two free variables."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.1-system-06",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "consistency",
    "statement": "A consistent linear system must have exactly one solution.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Consistent means uniquely solvable.",
    "explanation": "Consistent means only that at least one solution exists. A consistent system may have one solution or infinitely many solutions."
  },
  {
    "id": "1.1-system-07",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "consistency",
    "statement": "An inconsistent system has an empty solution set.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Inconsistent means the equations are merely inconvenient or redundant.",
    "explanation": "By definition, an inconsistent system has no solution, so its solution set is empty."
  },
  {
    "id": "1.1-system-08",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution",
    "statement": "If \\((x_1,x_2)=(1,2)\\) satisfies the first equation of a system but not the second, it is still a solution of the system.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Satisfying some of the equations makes a list of values a partial solution.",
    "explanation": "A solution must satisfy every equation at once. Failing even one equation disqualifies it completely."
  },
  {
    "id": "1.1-system-09",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution-count",
    "statement": "A linear system with real coefficients has no solution, exactly one solution, or infinitely many solutions.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A linear system can have any number of solutions.",
    "explanation": "These three cases are exhaustive. In particular, no such system has exactly two or exactly seventeen solutions."
  },
  {
    "id": "1.1-system-10",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution-set",
    "statement": "The solution set of a system of two equations consists of everything solving the first equation together with everything solving the second.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The solution set is the union of the individual equations' solution sets.",
    "explanation": "A solution has to satisfy both equations, so the solution set is the intersection of the two individual solution sets, not their union.",
    "counterexample": "The system \\(x=0,\\;x=1\\) has an equation solved by \\(x=0\\) and an equation solved by \\(x=1\\), yet nothing satisfies both, so the solution set is empty."
  },
  {
    "id": "1.1-matrix-01",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "coefficient-matrix",
    "statement": "The coefficient matrix of a system includes the constants on the right-hand side of the equations.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Coefficient matrix and augmented matrix are the same object.",
    "explanation": "The coefficient matrix contains only the coefficients of the variables. Appending the right-hand-side column produces the augmented matrix.",
    "why": {
      "prompt": "Which distinction is correct?",
      "choices": [
        "The augmented matrix omits the right-hand side.",
        "The coefficient matrix omits the right-hand side; the augmented matrix includes it.",
        "Both matrices must be square.",
        "The coefficient matrix always has one more column."
      ],
      "correct": 1
    }
  },
  {
    "id": "1.1-matrix-02",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "augmented-matrix",
    "statement": "For a system of \\(m\\) equations in \\(n\\) variables, its coefficient matrix is \\(m\\times n\\), while its augmented matrix has \\(m\\) rows and \\(n+1\\) columns.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Rows count variables and columns count equations.",
    "explanation": "There is one row per equation and one coefficient column per variable. The augmented matrix adds one right-hand-side column."
  },
  {
    "id": "1.1-matrix-03",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "matrix-dimensions",
    "statement": "An \\(m\\times n\\) matrix has \\(m\\) rows and \\(n\\) columns.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The order in matrix dimensions is columns by rows.",
    "explanation": "Matrix dimensions are always listed as rows by columns."
  },
  {
    "id": "1.1-matrix-04",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "matrix-vs-system",
    "statement": "An abstract matrix, with no system attached to it, is itself either consistent or inconsistent.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Terminology for systems automatically applies to matrices.",
    "explanation": "Consistency is a property of a system of equations. A matrix may represent an augmented matrix of a system, but an abstract matrix by itself is not a system.",
    "counterexample": "The same array of numbers can be studied simply as a matrix without assigning any right-hand-side column."
  },
  {
    "id": "1.1-matrix-05",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "augmented-matrix",
    "statement": "When forming an augmented matrix, each row may list its coefficients in whatever variable order is convenient for that equation.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The matrix is only a bookkeeping table, so the order within a row does not matter.",
    "explanation": "Every column must correspond to one fixed variable across all rows. If rows used different orderings, a column would no longer represent a single variable and row operations would lose their meaning."
  },
  {
    "id": "1.1-matrix-06",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "coefficient-matrix",
    "statement": "If a variable is absent from one of the equations, that equation's row still has an entry in that variable's column, namely \\(0\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Variables missing from an equation are simply skipped when building the matrix.",
    "explanation": "An absent variable has coefficient \\(0\\). Recording that zero is what keeps each column aligned with a single variable."
  },
  {
    "id": "1.1-matrix-07",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "matrix-dimensions",
    "statement": "A matrix with \\(4\\) rows and \\(7\\) columns is a \\(7\\times4\\) matrix.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Dimensions are listed as columns by rows.",
    "explanation": "Dimensions are always listed rows first, so this matrix is \\(4\\times7\\)."
  },
  {
    "id": "1.1-matrix-08",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "matrix-vs-system",
    "statement": "Elementary row operations can be applied to any matrix, whether or not it came from a system of equations.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Row operations only make sense for augmented matrices.",
    "explanation": "Row operations are defined on rectangular arrays of numbers. Reading the result back as a system is an extra step, available only when the matrix represents one."
  },
  {
    "id": "1.1-rowops-01",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-scaling",
    "statement": "Multiplying a row by \\(0\\) is an elementary row operation.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A row may be scaled by any scalar.",
    "explanation": "Row scaling must use a nonzero scalar. Multiplying by zero destroys information and cannot be undone."
  },
  {
    "id": "1.1-rowops-02",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-replacement",
    "statement": "Adding a multiple of one row to a different row is an elementary row operation.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Row replacement means replacing a row by an arbitrary new row.",
    "explanation": "This is the row-replacement operation: replace one row by itself plus a scalar multiple of another row."
  },
  {
    "id": "1.1-rowops-03",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-interchange",
    "statement": "Interchanging two equations in a system changes its solution set.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Changing the order of equations changes the system's solutions.",
    "explanation": "The order in which the equations are listed does not affect which values satisfy all of them."
  },
  {
    "id": "1.1-rowops-04",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "equivalent-systems",
    "statement": "If the augmented matrices of two systems are row equivalent, then the systems are equivalent.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Row operations can change the solution set.",
    "explanation": "Each elementary row operation replaces a system by one with the same solutions, so a sequence of such operations preserves the solution set.",
    "why": {
      "prompt": "What is the key reason?",
      "choices": [
        "Every elementary row operation is reversible and preserves the solution set.",
        "Every row-equivalent matrix is square.",
        "Row-equivalent matrices have identical entries.",
        "Equivalent systems must have the same equations in the same order."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.1-rowops-05",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-equivalence",
    "statement": "Row-equivalent matrices must have the same dimensions.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Row operations may add or remove rows or columns.",
    "explanation": "Elementary row operations change entries or row order, but they do not change the number of rows or columns."
  },
  {
    "id": "1.1-rowops-06",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-equivalence",
    "statement": "If \\(A\\) is row equivalent to \\(B\\), then \\(B\\) is row equivalent to \\(A\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Row equivalence only goes in the direction in which the operations were performed.",
    "explanation": "Every elementary row operation has an inverse elementary row operation, so the sequence can be reversed."
  },
  {
    "id": "1.1-rowops-07",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "equivalent-systems",
    "statement": "If two systems are equivalent, then their augmented matrices must be row equivalent.",
    "answer": false,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "The implication between row equivalence and equivalent systems automatically works both ways.",
    "explanation": "Row-equivalent augmented matrices always give equivalent systems, but the converse can fail. In particular, all inconsistent systems have the same empty solution set, while their augmented matrices need not have the same RREF.",
    "counterexample": "The systems \\(x=0,\\;0=1\\) and \\(y=0,\\;0=1\\) (in variables \\(x,y\\)) are both inconsistent, hence equivalent as systems, but their augmented matrices have different RREFs.",
    "why": {
      "prompt": "Why does the converse fail?",
      "choices": [
        "Every inconsistent system has the empty solution set, so systems with quite different augmented matrices can still be equivalent.",
        "Elementary row operations can change a system's solution set.",
        "Equivalent systems must have different numbers of equations.",
        "The augmented matrices of equivalent systems always have different sizes."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.1-rowops-08",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "equivalent-systems",
    "statement": "Suppose two systems, each consisting of \\(m\\) equations in the variables \\(x_1,\\dots,x_n\\), are both consistent and have the same solution set. Then their augmented matrices are row equivalent.",
    "answer": true,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "Because the converse fails in general, it must fail for consistent systems too.",
    "explanation": "For a consistent system, the solution set determines the reduced row echelon form of the augmented matrix. Two such systems of the same size therefore share an RREF, which makes their augmented matrices row equivalent. Consistency is exactly the hypothesis that was missing when the converse failed.",
    "why": {
      "prompt": "Why does assuming consistency repair the converse?",
      "choices": [
        "All inconsistent systems share the empty solution set, so that solution set carries no information about the augmented matrix.",
        "Consistent systems always have exactly one solution.",
        "Consistent systems always have square augmented matrices.",
        "Row operations behave differently on consistent systems."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.1-rowops-09",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-equivalence",
    "statement": "Any two matrices of the same size are row equivalent.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Row operations are powerful enough to turn any matrix into any other matrix of the same size.",
    "explanation": "Row operations preserve the reduced row echelon form, so two matrices with different reduced row echelon forms are never row equivalent.",
    "counterexample": "\\(\\begin{bmatrix}0&0\\\\0&0\\end{bmatrix}\\) and \\(\\begin{bmatrix}1&0\\\\0&1\\end{bmatrix}\\) are both \\(2\\times2\\), but no row operation can produce a nonzero entry from an all-zero matrix."
  },
  {
    "id": "1.1-rowops-10",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-equivalence",
    "statement": "A matrix is row equivalent only to those matrices obtained from it by a single elementary row operation.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Row equivalence describes one step rather than a sequence of steps.",
    "explanation": "Row equivalence allows any finite sequence of elementary row operations. A matrix is row equivalent to everything reachable in any number of steps, not just one."
  },
  {
    "id": "1.1-rowops-11",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-interchange",
    "statement": "Interchanging two rows is an elementary row operation, and performing the same interchange a second time restores the original matrix.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Undoing a row interchange requires some different operation.",
    "explanation": "Interchange is its own inverse. Swapping the same two rows again returns every entry to its original position."
  },
  {
    "id": "1.1-rowops-12",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-replacement",
    "statement": "In a matrix with three rows, replacing the first row by the sum of the second and third rows is an elementary row operation.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Any operation that builds a new row out of existing rows counts as row replacement.",
    "explanation": "Row replacement changes \\(R_i\\) into \\(R_i+cR_j\\), keeping the row being modified. Discarding the original first row destroys information and cannot be undone."
  },
  {
    "id": "1.1-rowops-13",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-scaling",
    "statement": "Multiplying every entry of a single row by \\(-3\\) is an elementary row operation.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A scaling factor has to be positive.",
    "explanation": "Row scaling permits any nonzero scalar, and \\(-3\\) is nonzero. The operation is undone by multiplying the same row by \\(-1/3\\)."
  },
  {
    "id": "1.2-ref-01",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref",
    "statement": "In row echelon form, every leading entry must equal \\(1\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "REF and RREF have the same requirements.",
    "explanation": "A leading entry in REF only needs to be nonzero. Requiring each leading entry to be \\(1\\) is part of reduced echelon form."
  },
  {
    "id": "1.2-ref-02",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref",
    "statement": "A matrix can be in row echelon form with a zero row above a nonzero row.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The location of zero rows does not matter in echelon form.",
    "explanation": "In echelon form, every nonzero row must occur above every zero row."
  },
  {
    "id": "1.2-ref-03",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref",
    "statement": "As you move down the nonzero rows of a matrix in echelon form, the leading entries move strictly to the right.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Leading entries may occur in the same column in different nonzero rows.",
    "explanation": "Each leading entry in a lower nonzero row must be to the right of the leading entry in the row above."
  },
  {
    "id": "1.2-ref-04",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref",
    "statement": "In row echelon form, every entry below a leading entry is zero.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Zeros below pivots are required only in RREF.",
    "explanation": "Zeros below each leading entry are already required in echelon form."
  },
  {
    "id": "1.2-ref-05",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref-vs-rref",
    "statement": "In row echelon form, every entry above a leading entry must be zero.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "REF already has zeros both above and below pivots.",
    "explanation": "Zeros above pivot locations are required for reduced echelon form, not ordinary echelon form."
  },
  {
    "id": "1.2-ref-06",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref-vs-rref",
    "statement": "Every matrix in reduced row echelon form is also in row echelon form.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The two forms are separate categories rather than one being a strengthening of the other.",
    "explanation": "Reduced echelon form imposes all of the echelon conditions and then adds two more: each leading entry equals \\(1\\), and each leading \\(1\\) is the only nonzero entry in its column."
  },
  {
    "id": "1.2-rref-01",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "rref",
    "statement": "In reduced row echelon form, a leading entry may be any nonzero scalar; it does not have to equal \\(1\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "REF and RREF place the same requirements on leading entries.",
    "explanation": "RREF requires each leading entry of a nonzero row to be \\(1\\). Ordinary REF allows other nonzero leading entries."
  },
  {
    "id": "1.2-rref-02",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "rref",
    "statement": "In reduced row echelon form, a leading \\(1\\) is the only nonzero entry in its column.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Only the entries below a leading 1 need to vanish in RREF.",
    "explanation": "RREF requires zeros both below and above each leading \\(1\\)."
  },
  {
    "id": "1.2-rref-03",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "unique-rref",
    "statement": "Every matrix is row equivalent to exactly one matrix in row echelon form.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The uniqueness theorem applies to REF rather than RREF.",
    "explanation": "A matrix can have many echelon forms. What is unique is its reduced row echelon form.",
    "counterexample": "Both \\(\\begin{bmatrix}1&2\\\\0&1\\end{bmatrix}\\) and \\(\\begin{bmatrix}1&0\\\\0&1\\end{bmatrix}\\) are echelon matrices and are row equivalent."
  },
  {
    "id": "1.2-rref-04",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "unique-rref",
    "statement": "Every matrix is row equivalent to a unique reduced row echelon form.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Different row-reduction choices can produce different RREFs.",
    "explanation": "Although the sequence of row operations is not unique, the final RREF is unique."
  },
  {
    "id": "1.2-rref-05",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "row-equivalence",
    "statement": "If two matrices are row equivalent, then they have the same reduced row echelon form.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Row-equivalent matrices can have unrelated canonical forms.",
    "explanation": "Row-equivalent matrices lie in the same row-equivalence class, and each class has one unique RREF."
  },
  {
    "id": "1.2-rref-06",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "row-equivalence",
    "statement": "If two matrices have the same reduced row echelon form, then they are row equivalent.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Sharing an RREF is weaker than row equivalence.",
    "explanation": "Each matrix is row equivalent to that common RREF, so reversing one sequence and composing the operations shows the two matrices are row equivalent."
  },
  {
    "id": "1.2-rref-07",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "rref",
    "statement": "A matrix all of whose entries are \\(0\\) is in reduced row echelon form.",
    "answer": true,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "Reduced row echelon form requires at least one leading \\(1\\).",
    "explanation": "Every defining condition concerns nonzero rows and their leading entries. A zero matrix has no nonzero rows, so all of the conditions hold vacuously and the matrix is already in reduced row echelon form."
  },
  {
    "id": "1.2-pivot-01",
    "section": "1.2",
    "topic": "Pivot positions",
    "concept": "pivot-position",
    "statement": "A pivot position of \\(A\\) is determined by where a leading \\(1\\) occurs in the RREF of \\(A\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A pivot position is any location containing a nonzero entry in the original matrix.",
    "explanation": "Pivot positions are locations in the original matrix corresponding to leading \\(1\\)s in its unique RREF."
  },
  {
    "id": "1.2-pivot-02",
    "section": "1.2",
    "topic": "Pivot positions",
    "concept": "pivot-column",
    "statement": "Every nonzero column of a matrix is a pivot column.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A nonzero column automatically contains a pivot position.",
    "explanation": "A nonzero column may fail to contain a pivot position. Pivot columns are determined by the locations of leading \\(1\\)s in the RREF."
  },
  {
    "id": "1.2-pivot-03",
    "section": "1.2",
    "topic": "Pivot positions",
    "concept": "pivot-position",
    "statement": "The pivot positions of a matrix can depend on which legal sequence of row operations you choose.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Because row-reduction paths differ, pivot locations can differ.",
    "explanation": "The RREF is unique, so the locations of its leading \\(1\\)s—and therefore the pivot positions—are fixed."
  },
  {
    "id": "1.2-pivot-04",
    "section": "1.2",
    "topic": "Pivot positions",
    "concept": "pivot-column",
    "statement": "A matrix cannot have more pivot columns than it has rows.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The number of pivot columns is limited only by the number of columns.",
    "explanation": "Leading entries in an echelon form move strictly down and to the right, so each pivot position occupies a row of its own. The number of pivots is therefore at most the number of rows."
  },
  {
    "id": "1.2-gauss-01",
    "section": "1.2",
    "topic": "Gaussian elimination",
    "concept": "gaussian-elimination",
    "statement": "Gaussian elimination uses elementary row operations to produce an echelon form of a matrix.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Gaussian elimination requires going all the way to RREF.",
    "explanation": "The forward phase of Gaussian elimination produces an echelon form. Further reduction can be used when RREF is desired."
  },
  {
    "id": "1.2-gauss-02",
    "section": "1.2",
    "topic": "Gaussian elimination",
    "concept": "gaussian-elimination",
    "statement": "Two people who each row reduce the same matrix correctly must have used the same sequence of elementary row operations.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "There is only one correct path through row reduction.",
    "explanation": "Many different sequences of operations reach an echelon form, and many different sequences reach the reduced echelon form. The final reduced echelon form is unique; the route to it is not."
  },
  {
    "id": "1.2-variables-01",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "basic-variable",
    "statement": "In a linear system, a basic variable corresponds to a pivot column of the coefficient matrix.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A pivot in the augmented column represents a basic variable.",
    "explanation": "Variables correspond to columns of the coefficient matrix. A variable is basic when its coefficient column is a pivot column."
  },
  {
    "id": "1.2-variables-02",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "basic-variable",
    "statement": "Every variable whose coefficient column contains at least one nonzero entry is a basic variable.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Any nonzero coefficient column must be a pivot column.",
    "explanation": "A variable is basic only when its coefficient column is a pivot column. A nonpivot column can contain nonzero entries; its variable is free."
  },
  {
    "id": "1.2-variables-03",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "free-variable",
    "statement": "In a consistent system, once values are chosen for all free variables, the values of the basic variables are uniquely determined.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Choosing free variables may still leave basic variables undetermined.",
    "explanation": "After row reduction, each basic variable is expressed in terms of the free variables. Fixing all free-variable values therefore fixes every basic variable.",
    "why": {
      "prompt": "What does 'free' mean here?",
      "choices": [
        "A free variable can be assigned a value, after which the basic variables are determined.",
        "A free variable never appears in any equation.",
        "A free variable must equal zero.",
        "A free variable corresponds to a pivot column."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-variables-04",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "basic-variable",
    "statement": "The number of basic variables equals the number of pivot columns in the coefficient matrix.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The augmented column can add a basic variable.",
    "explanation": "There is one variable for each coefficient column, and exactly the variables in pivot columns are basic."
  },
  {
    "id": "1.2-variables-05",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "free-variable",
    "statement": "When writing the solution set of a consistent system, each free variable must be assigned the value \\(0\\).",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Setting free variables to zero is part of the procedure rather than one choice among many.",
    "explanation": "A free variable may take any value; that is what makes it free. Setting them all to \\(0\\) produces one particular solution, but describing the whole solution set requires keeping them as parameters."
  },
  {
    "id": "1.2-existence-01",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "consistency-test",
    "statement": "A system is inconsistent exactly when the rightmost column of its augmented matrix is a pivot column.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "A pivot in the augmented column is harmless.",
    "explanation": "A pivot in the augmented column produces an echelon row of the form \\([0\\ \\cdots\\ 0\\mid b]\\) with \\(b\\ne0\\), which represents an impossible equation \\(0=b\\).",
    "why": {
      "prompt": "Which row signals the problem?",
      "choices": [
        "\\([0\\ \\cdots\\ 0\\mid b]\\) with \\(b\\ne0\\)",
        "\\([0\\ \\cdots\\ 0\\mid 0]\\)",
        "Any row containing a zero",
        "Any row whose first entry is not \\(1\\)"
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-existence-02",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "consistency-test",
    "statement": "An echelon row \\([0\\ 0\\ 0\\mid 5]\\) can be ignored when deciding whether the corresponding system is consistent.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A row with no variable terms never affects the solution set.",
    "explanation": "That row represents \\(0=5\\), which is impossible, so it proves the system is inconsistent."
  },
  {
    "id": "1.2-existence-03",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "consistency-test",
    "statement": "An echelon row \\([0\\ 0\\ 0\\mid 0]\\) proves that the corresponding system is inconsistent.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Any zero row indicates inconsistency.",
    "explanation": "That row represents \\(0=0\\), which imposes no additional restriction and causes no inconsistency."
  },
  {
    "id": "1.2-existence-04",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "unique-solution",
    "statement": "If a system is consistent and has no free variables, then it has a unique solution.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A consistent system without free variables might still have many solutions.",
    "explanation": "With no free variables, every variable is basic and is uniquely determined."
  },
  {
    "id": "1.2-existence-05",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "infinite-solutions",
    "statement": "If a system is consistent and has at least one free variable, then it has infinitely many solutions.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "One free variable gives only a few extra solutions.",
    "explanation": "A free variable may be assigned infinitely many different real values, and each choice determines a solution."
  },
  {
    "id": "1.2-existence-06",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "unique-solution",
    "statement": "If a system has no free variables, then it must have a unique solution.",
    "answer": false,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "The consistency hypothesis in the existence-and-uniqueness theorem can be omitted.",
    "explanation": "The system could be inconsistent because the augmented column is a pivot column. 'No free variables' controls uniqueness only after existence is known.",
    "counterexample": "\\(x=0\\) together with \\(0=1\\) has no free variable \\(x\\), but it has no solution."
  },
  {
    "id": "1.2-existence-07",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "unique-solution",
    "statement": "A pivot in every coefficient column guarantees that a system has a unique solution.",
    "answer": false,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "Pivots in all variable columns guarantee both existence and uniqueness.",
    "explanation": "Pivots in all coefficient columns mean there are no free variables, but the system may still be inconsistent if the augmented column is also a pivot column.",
    "counterexample": "\\(x=0,\\;y=0,\\;0=1\\) has pivots in both coefficient columns and is inconsistent.",
    "why": {
      "prompt": "Which half of existence and uniqueness does the statement leave unsettled?",
      "choices": [
        "Existence: the augmented column may itself be a pivot column, making the system inconsistent.",
        "Uniqueness: free variables may still remain.",
        "Neither; the statement is correct for square systems.",
        "Existence: a system with no free variables cannot be written in parametric form."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-existence-08",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "consistency-test",
    "statement": "If the rightmost column of an augmented matrix is not a pivot column, then the corresponding system is consistent.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Consistency requires a pivot in every row or every coefficient column.",
    "explanation": "The absence of a pivot in the augmented column means row reduction never produces an impossible equation \\(0=b\\) with \\(b\\ne0\\)."
  },
  {
    "id": "1.2-existence-09",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "unique-solution",
    "statement": "If a system is consistent and every column of its coefficient matrix is a pivot column, then the system has exactly one solution.",
    "answer": true,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "Adding the consistency hypothesis is still not enough to guarantee uniqueness.",
    "explanation": "Pivots in every coefficient column mean there are no free variables, which settles uniqueness once existence is known. Consistency supplies precisely that missing piece."
  },
  {
    "id": "1.2-existence-10",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "infinite-solutions",
    "statement": "If a consistent system has more variables than equations, then it has infinitely many solutions.",
    "answer": true,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "Having more variables than equations by itself tells you nothing about the number of solutions.",
    "explanation": "Each pivot position occupies a row of its own, so a system of \\(m\\) equations has at most \\(m\\) pivots. With \\(n>m\\) variables, some coefficient column has no pivot and its variable is free. A consistent system with a free variable has infinitely many solutions.",
    "why": {
      "prompt": "Where does the hypothesis of consistency do its work?",
      "choices": [
        "Without it the system could instead have no solutions at all.",
        "Without it there would be no free variables.",
        "Without it the coefficient matrix would not be defined.",
        "Without it the system would have exactly one solution."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-parametric-01",
    "section": "1.2",
    "topic": "Parametric solution sets",
    "concept": "parametric-form",
    "statement": "For a consistent system, RREF makes it possible to express each basic variable in terms of the free variables.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Free variables must be solved in terms of basic variables.",
    "explanation": "The usual parametric description treats the free variables as parameters and solves the pivot equations for the basic variables."
  },
  {
    "id": "1.2-parametric-02",
    "section": "1.2",
    "topic": "Parametric solution sets",
    "concept": "ref-suffices",
    "statement": "If your only goal is to decide whether a system is consistent, reaching row echelon form is enough; continuing to RREF is unnecessary.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Every row-reduction problem must continue to RREF.",
    "explanation": "In REF you can already see whether an impossible row \\([0\\ \\cdots\\ 0\\mid b]\\), \\(b\\ne0\\), occurs. RREF is useful for reading an explicit solution description more directly.",
    "why": {
      "prompt": "Why does REF suffice for existence?",
      "choices": [
        "The inconsistency row is already visible in echelon form.",
        "Every echelon matrix is already reduced.",
        "Free variables disappear in echelon form.",
        "RREF can change whether solutions exist."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-parametric-03",
    "section": "1.2",
    "topic": "Parametric solution sets",
    "concept": "parametric-form",
    "statement": "It is mathematically impossible to obtain a parametric description of a solution set from REF without first computing RREF.",
    "answer": false,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "RREF is logically necessary rather than a convenient canonical form.",
    "explanation": "RREF makes the parametric form easy to read off, but REF together with back-substitution can also produce a parametric description. In this course, reducing to RREF is often the cleanest standard procedure.",
    "why": {
      "prompt": "What makes the statement too strong?",
      "choices": [
        "Back-substitution turns an echelon form into a parametric description without computing RREF.",
        "Echelon forms never have free variables.",
        "Echelon form and reduced echelon form are the same thing.",
        "Parametric descriptions do not exist for systems with free variables."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-parametric-04",
    "section": "1.2",
    "topic": "Parametric solution sets",
    "concept": "ref-suffices",
    "statement": "Echelon form is enough to decide whether a system is consistent, but you cannot tell from echelon form whether the solution is unique.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Uniqueness can only be read off from the reduced echelon form.",
    "explanation": "Pivot positions are already visible in any echelon form, so you can see whether every coefficient column has a pivot. That decides whether free variables exist, and therefore whether a consistent system has one solution or infinitely many."
  },
  {
    "id": "1.3-vector-01",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "column-vector",
    "statement": "A vector in \\(\\mathbb{R}^n\\) may be regarded as an \\(n\\times1\\) matrix.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Vectors and matrices are unrelated kinds of object.",
    "explanation": "A column vector is by definition a matrix with a single column. A vector in \\(\\mathbb{R}^n\\) has \\(n\\) entries, so it is \\(n\\times1\\)."
  },
  {
    "id": "1.3-vector-02",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "column-vector",
    "statement": "\\(\\begin{bmatrix}1\\\\2\\end{bmatrix}\\) and \\(\\begin{bmatrix}1&2\\end{bmatrix}\\) are the same object.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The arrangement of entries is only a matter of typography.",
    "explanation": "The first is \\(2\\times1\\) and the second is \\(1\\times2\\). They carry the same numbers but are matrices of different sizes, and only the first is a vector in \\(\\mathbb{R}^2\\)."
  },
  {
    "id": "1.3-vector-03",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "vector-equality",
    "statement": "Two vectors in \\(\\mathbb{R}^n\\) are equal exactly when their corresponding entries agree.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Equality of vectors is about length or direction rather than entries.",
    "explanation": "Equality is checked entry by entry: the vectors are equal when the first entries agree, the second entries agree, and so on."
  },
  {
    "id": "1.3-vector-04",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "vector-equality",
    "statement": "Two vectors are equal whenever they contain the same numbers, even if those numbers are listed in a different order.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A vector is an unordered collection of numbers.",
    "explanation": "The order of the entries is part of the data. Corresponding entries must agree position by position.",
    "counterexample": "\\(\\begin{bmatrix}1\\\\2\\end{bmatrix}\\) and \\(\\begin{bmatrix}2\\\\1\\end{bmatrix}\\) are different vectors, and as points in the plane they are different points."
  },
  {
    "id": "1.3-vector-05",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "vector-addition",
    "statement": "The sum \\(\\begin{bmatrix}1\\\\2\\end{bmatrix}+\\begin{bmatrix}3\\\\4\\\\5\\end{bmatrix}\\) is a vector in \\(\\mathbb{R}^3\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Vectors of different sizes can be added by padding the shorter one.",
    "explanation": "Addition is defined only for vectors with the same number of entries. This sum is undefined, so it is not a vector in any \\(\\mathbb{R}^m\\)."
  },
  {
    "id": "1.3-vector-06",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "vector-addition",
    "statement": "Vectors in \\(\\mathbb{R}^n\\) are added entry by entry.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Addition of vectors requires a geometric construction rather than arithmetic.",
    "explanation": "The \\(i\\)th entry of \\(u+v\\) is the sum of the \\(i\\)th entries of \\(u\\) and \\(v\\). The parallelogram picture describes this same operation geometrically."
  },
  {
    "id": "1.3-vector-07",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "scalar-multiple",
    "statement": "Multiplying a vector by a scalar multiplies every entry of that vector by the scalar.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A scalar multiplies only the first entry, or only some entries.",
    "explanation": "If \\(c\\) is a scalar, then \\(cv\\) is formed by multiplying each entry of \\(v\\) by \\(c\\). The result has the same number of entries as \\(v\\)."
  },
  {
    "id": "1.3-vector-08",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "scalar-multiple",
    "statement": "If \\(c\\) is a nonzero scalar and \\(v\\) is a nonzero vector, then \\(cv\\) can still be the zero vector.",
    "answer": false,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "A product can vanish without either factor vanishing.",
    "explanation": "Each entry of \\(cv\\) is \\(cv_i\\). If \\(cv_i=0\\) and \\(c\\ne0\\), then \\(v_i=0\\). If every entry of \\(cv\\) were zero, every entry of \\(v\\) would be zero, contradicting \\(v\\ne0\\)."
  },
  {
    "id": "1.3-vector-09",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "zero-vector",
    "statement": "The zero vector in \\(\\mathbb{R}^n\\) is the vector whose entries are all \\(0\\), and \\(v+0=v\\) holds for every \\(v\\) in \\(\\mathbb{R}^n\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The zero vector is a special symbol rather than an actual vector with entries.",
    "explanation": "The zero vector is an ordinary vector, and adding it entry by entry changes nothing. That is what makes it the additive identity."
  },
  {
    "id": "1.3-vector-10",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "zero-vector",
    "statement": "The scalar \\(0\\) and the zero vector in \\(\\mathbb{R}^n\\) are the same object.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Anything written as \\(0\\) denotes the same thing.",
    "explanation": "A scalar is a single number; the zero vector is an element of \\(\\mathbb{R}^n\\) with \\(n\\) entries. They are used differently: \\(0v\\) multiplies by a scalar, while \\(v+0\\) adds a vector."
  },
  {
    "id": "1.3-geom-01",
    "section": "1.3",
    "topic": "Geometry of vectors",
    "concept": "vector-geometry",
    "statement": "A vector in \\(\\mathbb{R}^2\\) can be pictured as the point in the plane whose coordinates are its entries.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Vectors and points are unrelated.",
    "explanation": "Identifying a vector with a point, or with an arrow from the origin to that point, is the standard picture for \\(\\mathbb{R}^2\\) and \\(\\mathbb{R}^3\\)."
  },
  {
    "id": "1.3-geom-02",
    "section": "1.3",
    "topic": "Geometry of vectors",
    "concept": "vector-geometry",
    "statement": "If neither of \\(u\\) and \\(v\\) is a scalar multiple of the other, then \\(u+v\\) is the fourth vertex of the parallelogram whose other three vertices are \\(0\\), \\(u\\), and \\(v\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The parallelogram rule is a separate operation from entrywise addition.",
    "explanation": "This is the parallelogram rule, and it is a picture of the same entrywise sum. The hypothesis rules out the degenerate case in which the three points are collinear and no parallelogram is formed."
  },
  {
    "id": "1.3-geom-03",
    "section": "1.3",
    "topic": "Geometry of vectors",
    "concept": "vector-geometry",
    "statement": "Multiplying a vector by a negative scalar reverses its direction and always makes it shorter.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "A negative scalar shrinks a vector because negative numbers are small.",
    "explanation": "The direction reverses, but the length is scaled by the size of the scalar, not its sign. A factor larger than \\(1\\) in size makes the vector longer.",
    "counterexample": "\\(-3v\\) points opposite to \\(v\\) and is three times as long."
  },
  {
    "id": "1.3-algebra-01",
    "section": "1.3",
    "topic": "Vector algebra",
    "concept": "vector-algebra",
    "statement": "For every vector \\(v\\) in \\(\\mathbb{R}^n\\) and all scalars \\(c\\) and \\(d\\), \\((c+d)v=cv+dv\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Scalar multiplication distributes only over vector addition, not over addition of scalars.",
    "explanation": "Both distributive laws hold: \\(c(u+v)=cu+cv\\) and \\((c+d)v=cv+dv\\). Each can be checked one entry at a time."
  },
  {
    "id": "1.3-algebra-02",
    "section": "1.3",
    "topic": "Vector algebra",
    "concept": "vector-algebra",
    "statement": "For all vectors \\(u,v\\) in \\(\\mathbb{R}^n\\) and every scalar \\(c\\), \\(c(u+v)=cu+v\\).",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "A scalar in front of a sum attaches to only the first term.",
    "explanation": "Distributing \\(c\\) must reach both terms: \\(c(u+v)=cu+cv\\).",
    "counterexample": "Take \\(c=2\\), \\(u=v=\\begin{bmatrix}1\\\\0\\end{bmatrix}\\). Then \\(c(u+v)=\\begin{bmatrix}4\\\\0\\end{bmatrix}\\) but \\(cu+v=\\begin{bmatrix}3\\\\0\\end{bmatrix}\\)."
  },
  {
    "id": "1.3-algebra-03",
    "section": "1.3",
    "topic": "Vector algebra",
    "concept": "vector-algebra",
    "statement": "The expression \\(v-w\\) is shorthand for \\(v+(-1)w\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Subtraction of vectors is a separate operation with its own definition.",
    "explanation": "Only addition and scalar multiplication are defined. Subtraction is an abbreviation, and \\(-w\\) means \\((-1)w\\)."
  },
  {
    "id": "1.3-algebra-04",
    "section": "1.3",
    "topic": "Vector algebra",
    "concept": "vector-algebra",
    "statement": "For vectors \\(u\\) and \\(v\\) in \\(\\mathbb{R}^n\\), the vectors \\(u-v\\) and \\(v-u\\) are equal.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Vector addition is commutative, so vector subtraction must be too.",
    "explanation": "Addition commutes, but subtraction does not. In fact \\(v-u=-(u-v)\\), and these agree only when \\(u=v\\).",
    "counterexample": "With \\(u=\\begin{bmatrix}1\\\\0\\end{bmatrix}\\) and \\(v=\\begin{bmatrix}0\\\\0\\end{bmatrix}\\), \\(u-v=\\begin{bmatrix}1\\\\0\\end{bmatrix}\\) but \\(v-u=\\begin{bmatrix}-1\\\\0\\end{bmatrix}\\)."
  },
  {
    "id": "1.3-lincomb-01",
    "section": "1.3",
    "topic": "Linear combinations",
    "concept": "linear-combination",
    "statement": "A linear combination of \\(v_1,\\dots,v_p\\) is any vector of the form \\(c_1v_1+\\cdots+c_pv_p\\), where \\(c_1,\\dots,c_p\\) are scalars.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A linear combination requires some special choice of weights.",
    "explanation": "The weights may be any scalars at all. Different choices of weights produce different linear combinations of the same list of vectors."
  },
  {
    "id": "1.3-lincomb-02",
    "section": "1.3",
    "topic": "Linear combinations",
    "concept": "linear-combination",
    "statement": "The weights in a linear combination are required to be positive.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Weights behave like proportions and so must be positive.",
    "explanation": "Weights are arbitrary scalars. They may be negative or zero, which is what allows expressions such as \\(2v_1-3v_2\\)."
  },
  {
    "id": "1.3-lincomb-03",
    "section": "1.3",
    "topic": "Linear combinations",
    "concept": "linear-combination",
    "statement": "The zero vector is a linear combination of any nonempty list of vectors \\(v_1,\\dots,v_p\\) in \\(\\mathbb{R}^n\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Producing the zero vector requires the vectors themselves to be special.",
    "explanation": "Choosing every weight to be \\(0\\) gives \\(0v_1+\\cdots+0v_p=0\\). No assumption about the vectors is needed."
  },
  {
    "id": "1.3-lincomb-04",
    "section": "1.3",
    "topic": "Linear combinations",
    "concept": "linear-combination",
    "statement": "Each of the vectors \\(v_1,\\dots,v_p\\) is itself a linear combination of \\(v_1,\\dots,v_p\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "A linear combination must genuinely mix several vectors together.",
    "explanation": "Put weight \\(1\\) on the vector you want and weight \\(0\\) on all the others. For instance \\(v_2=0v_1+1v_2+0v_3+\\cdots+0v_p\\)."
  },
  {
    "id": "1.3-lincomb-05",
    "section": "1.3",
    "topic": "Linear combinations",
    "concept": "linear-combination",
    "statement": "A linear combination of vectors in \\(\\mathbb{R}^n\\) is a scalar.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Combining vectors with numerical weights produces a number.",
    "explanation": "Scalar multiples of vectors are vectors, and sums of vectors are vectors. A linear combination of vectors in \\(\\mathbb{R}^n\\) is again a vector in \\(\\mathbb{R}^n\\)."
  },
  {
    "id": "1.3-veceq-01",
    "section": "1.3",
    "topic": "Vector equations",
    "concept": "vector-equation",
    "statement": "The vector equation \\(x_1a_1+\\cdots+x_na_n=b\\) has the same solution set as the linear system whose augmented matrix is \\(\\begin{bmatrix}a_1&\\cdots&a_n&b\\end{bmatrix}\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Vector equations are a separate topic from systems of equations.",
    "explanation": "Comparing the two sides entry by entry turns the single vector equation into one scalar equation per entry, and those are exactly the equations of that system.",
    "why": {
      "prompt": "What makes the two problems the same?",
      "choices": [
        "Equality of vectors is equality in every entry, and each entry gives one equation of the system.",
        "Every vector equation has exactly one solution.",
        "The vectors \\(a_1,\\dots,a_n\\) must be the columns of an identity matrix.",
        "Row operations convert vector equations into scalar equations."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.3-veceq-02",
    "section": "1.3",
    "topic": "Vector equations",
    "concept": "vector-equation",
    "statement": "Deciding whether \\(b\\) is a linear combination of \\(a_1,\\dots,a_n\\) requires a technique different from solving a linear system.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Questions phrased with vectors need vector-specific methods.",
    "explanation": "Asking whether such weights exist is asking whether the vector equation \\(x_1a_1+\\cdots+x_na_n=b\\) is solvable, which is asking whether the system with augmented matrix \\(\\begin{bmatrix}a_1&\\cdots&a_n&b\\end{bmatrix}\\) is consistent. Row reduction answers it."
  },
  {
    "id": "1.3-veceq-03",
    "section": "1.3",
    "topic": "Vector equations",
    "concept": "vector-equation",
    "statement": "If the vector equation \\(x_1a_1+x_2a_2=b\\) has a solution, then the weights \\(x_1,x_2\\) are uniquely determined.",
    "answer": false,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "Existence of a representation as a linear combination forces that representation to be unique.",
    "explanation": "Solvability and uniqueness are separate questions here, exactly as they are for systems. The corresponding system may have a free variable.",
    "counterexample": "With \\(a_1=a_2=\\begin{bmatrix}1\\\\0\\end{bmatrix}\\) and \\(b=\\begin{bmatrix}1\\\\0\\end{bmatrix}\\), every pair with \\(x_1+x_2=1\\) works.",
    "why": {
      "prompt": "Which feature of the corresponding system causes the weights to be non-unique?",
      "choices": [
        "The system has a free variable.",
        "The system is inconsistent.",
        "The system has more equations than unknowns.",
        "The augmented column is a pivot column."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.3-span-01",
    "section": "1.3",
    "topic": "Span",
    "concept": "span",
    "statement": "\\(\\operatorname{Span}\\{v_1,\\dots,v_p\\}\\) is the set of all linear combinations of \\(v_1,\\dots,v_p\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The span is just the list of vectors you started with.",
    "explanation": "The span collects every vector that can be written as \\(c_1v_1+\\cdots+c_pv_p\\) for some choice of scalars."
  },
  {
    "id": "1.3-span-02",
    "section": "1.3",
    "topic": "Span",
    "concept": "span",
    "statement": "\\(b\\) belongs to \\(\\operatorname{Span}\\{a_1,\\dots,a_n\\}\\) exactly when the system with augmented matrix \\(\\begin{bmatrix}a_1&\\cdots&a_n&b\\end{bmatrix}\\) is inconsistent.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Membership in a span corresponds to inconsistency rather than consistency.",
    "explanation": "It is the other way around. Membership means suitable weights exist, so the system must be consistent.",
    "why": {
      "prompt": "What does consistency of that system mean here?",
      "choices": [
        "Weights exist that express \\(b\\) as a linear combination of \\(a_1,\\dots,a_n\\).",
        "The vectors \\(a_1,\\dots,a_n\\) are all nonzero.",
        "\\(b\\) is one of the vectors \\(a_1,\\dots,a_n\\).",
        "The span is all of \\(\\mathbb{R}^n\\)."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.3-span-03",
    "section": "1.3",
    "topic": "Span",
    "concept": "span",
    "statement": "\\(\\operatorname{Span}\\{u,v\\}\\) consists of exactly three vectors: \\(u\\), \\(v\\), and \\(u+v\\).",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The span is a short list built from the obvious combinations.",
    "explanation": "Every choice of weights is allowed, so the span also contains \\(2u\\), \\(-v\\), \\(3u-7v\\), the zero vector, and infinitely many others whenever \\(u\\) or \\(v\\) is nonzero."
  },
  {
    "id": "1.3-span-04",
    "section": "1.3",
    "topic": "Span",
    "concept": "span",
    "statement": "If \\(v\\) belongs to \\(\\operatorname{Span}\\{u\\}\\), then \\(\\operatorname{Span}\\{u,v\\}=\\operatorname{Span}\\{u\\}\\).",
    "answer": true,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "Adding another vector to a list always enlarges the span.",
    "explanation": "Write \\(v=cu\\). Then \\(au+bv=(a+bc)u\\), so every combination of \\(u\\) and \\(v\\) is already a multiple of \\(u\\). The reverse containment holds by taking \\(b=0\\), so the two spans are equal.",
    "why": {
      "prompt": "Why does adding \\(v\\) contribute nothing new?",
      "choices": [
        "\\(v\\) is already a multiple of \\(u\\), so any combination of \\(u\\) and \\(v\\) collapses to a multiple of \\(u\\).",
        "A span can never contain more than one vector.",
        "\\(v\\) must be the zero vector.",
        "Spans are unchanged by adding any vector whatsoever."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.3-span-05",
    "section": "1.3",
    "topic": "Span",
    "concept": "span",
    "statement": "\\(\\operatorname{Span}\\{v_1,\\dots,v_p\\}\\) always contains the zero vector.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The span contains the zero vector only when one of the \\(v_i\\) is zero.",
    "explanation": "Taking all weights equal to \\(0\\) produces the zero vector, whatever the vectors \\(v_1,\\dots,v_p\\) happen to be."
  },
  {
    "id": "1.3-spangeom-01",
    "section": "1.3",
    "topic": "Span",
    "concept": "span-geometry",
    "statement": "If \\(v\\) is a nonzero vector in \\(\\mathbb{R}^3\\), then \\(\\operatorname{Span}\\{v\\}\\) is a line through the origin.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The span of one vector is just that single arrow.",
    "explanation": "The span is the set of all multiples \\(cv\\). As \\(c\\) ranges over the real numbers these trace out the whole line through the origin in the direction of \\(v\\)."
  },
  {
    "id": "1.3-spangeom-02",
    "section": "1.3",
    "topic": "Span",
    "concept": "span-geometry",
    "statement": "If \\(u\\) and \\(v\\) are nonzero vectors in \\(\\mathbb{R}^3\\), then \\(\\operatorname{Span}\\{u,v\\}\\) is a plane through the origin.",
    "answer": false,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "Two nonzero vectors always span a two-dimensional set.",
    "explanation": "Being nonzero is not enough. If one vector is a multiple of the other, the two of them span only a line.",
    "counterexample": "Take \\(u=v=\\begin{bmatrix}1\\\\0\\\\0\\end{bmatrix}\\). Both are nonzero, but their span is a line, not a plane.",
    "why": {
      "prompt": "Which hypothesis is missing?",
      "choices": [
        "Neither vector may be a scalar multiple of the other.",
        "Both vectors must have three nonzero entries.",
        "The vectors must be perpendicular.",
        "The vectors must have the same length."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.3-spangeom-03",
    "section": "1.3",
    "topic": "Span",
    "concept": "span-geometry",
    "statement": "If \\(u\\) and \\(v\\) are vectors in \\(\\mathbb{R}^3\\) and neither is a scalar multiple of the other, then \\(\\operatorname{Span}\\{u,v\\}\\) is a plane containing the origin.",
    "answer": true,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "Ruling out the degenerate case is not enough to guarantee a plane.",
    "explanation": "With that hypothesis the two vectors point in genuinely different directions, and the combinations \\(au+bv\\) sweep out a plane. It passes through the origin because \\(a=b=0\\) is allowed."
  },
  {
    "id": "1.3-spangeom-04",
    "section": "1.3",
    "topic": "Span",
    "concept": "span-geometry",
    "statement": "\\(\\operatorname{Span}\\{0\\}\\) is a line through the origin.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The span of a single vector is always a line.",
    "explanation": "Every multiple of the zero vector is again the zero vector, so this span is the single point \\(\\{0\\}\\). A line requires the vector being spanned to be nonzero."
  },
  {
    "id": "1.3-vector-11",
    "section": "1.3",
    "topic": "Vectors",
    "concept": "column-vector",
    "statement": "Every matrix is a vector.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Because vectors are matrices, the two words describe the same collection of objects.",
    "explanation": "Vectors are exactly the matrices with a single column. A matrix with two or more columns is not a vector, so the containment goes only one way."
  },
  {
    "id": "1.3-geom-04",
    "section": "1.3",
    "topic": "Geometry of vectors",
    "concept": "vector-geometry",
    "statement": "If \\(v\\) is a nonzero vector, then \\(-v\\) points in the same direction as \\(v\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Negating a vector changes only its length.",
    "explanation": "\\(-v\\) is \\((-1)v\\), which reverses direction while keeping the length the same. It points opposite to \\(v\\)."
  },
  {
    "id": "1.3-algebra-05",
    "section": "1.3",
    "topic": "Vector algebra",
    "concept": "vector-algebra",
    "statement": "For every vector \\(v\\) in \\(\\mathbb{R}^n\\), \\(1v=0\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Confusing the scalar that acts as an identity with the one that annihilates.",
    "explanation": "Multiplying by the scalar \\(1\\) leaves a vector unchanged: \\(1v=v\\). It is the scalar \\(0\\) that produces the zero vector."
  },
  {
    "id": "1.3-algebra-06",
    "section": "1.3",
    "topic": "Vector algebra",
    "concept": "vector-algebra",
    "statement": "For all vectors \\(u,v,w\\) in \\(\\mathbb{R}^n\\), \\((u+v)+w=u+(v+w)\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The grouping of a sum of three vectors can change the result.",
    "explanation": "Vector addition is associative, since it is carried out entry by entry and addition of real numbers is associative. This is why a sum of several vectors can be written without parentheses."
  },
  {
    "id": "1.3-lincomb-06",
    "section": "1.3",
    "topic": "Linear combinations",
    "concept": "linear-combination",
    "statement": "If \\(y\\) is a linear combination of \\(v_1,v_2\\), then \\(y\\) is also a linear combination of \\(v_1,v_2,v_3\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "A linear combination must use every vector on the list.",
    "explanation": "Write \\(y=c_1v_1+c_2v_2\\) and then append the term \\(0v_3\\). Enlarging the list can never remove anything from the span."
  },
  {
    "id": "1.3-veceq-04",
    "section": "1.3",
    "topic": "Vector equations",
    "concept": "vector-equation",
    "statement": "Asking whether \\(b\\) lies in \\(\\operatorname{Span}\\{a_1,\\dots,a_n\\}\\) and asking whether the system with augmented matrix \\(\\begin{bmatrix}a_1&\\cdots&a_n&b\\end{bmatrix}\\) is consistent are the same question.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Span is a geometric notion that has to be investigated separately from row reduction.",
    "explanation": "\\(b\\) is in the span exactly when weights exist with \\(x_1a_1+\\cdots+x_na_n=b\\), and that vector equation has the same solution set as the system with that augmented matrix. So consistency answers the span question."
  },
  {
    "id": "1.4-prod-01",
    "section": "1.4",
    "topic": "The product Ax",
    "concept": "matrix-vector-product",
    "statement": "If \\(A\\) has columns \\(a_1,\\dots,a_n\\) and \\(x\\) is in \\(\\mathbb{R}^n\\), then \\(Ax=x_1a_1+\\cdots+x_na_n\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The product \\(Ax\\) is an unrelated bookkeeping operation.",
    "explanation": "This is the definition of the matrix-vector product: the columns of \\(A\\) are combined using the entries of \\(x\\) as weights."
  },
  {
    "id": "1.4-prod-02",
    "section": "1.4",
    "topic": "The product Ax",
    "concept": "matrix-vector-product",
    "statement": "The product \\(Ax\\) is defined for every matrix \\(A\\) and every vector \\(x\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Sizes never obstruct the matrix-vector product.",
    "explanation": "The weights come from the entries of \\(x\\), one for each column of \\(A\\). So \\(Ax\\) is defined only when the number of entries of \\(x\\) equals the number of columns of \\(A\\)."
  },
  {
    "id": "1.4-prod-03",
    "section": "1.4",
    "topic": "The product Ax",
    "concept": "matrix-vector-product",
    "statement": "If \\(A\\) is \\(m\\times n\\) and \\(x\\) is in \\(\\mathbb{R}^n\\), then \\(Ax\\) is in \\(\\mathbb{R}^m\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The output of \\(Ax\\) lives in the same space as \\(x\\).",
    "explanation": "\\(Ax\\) is a linear combination of the columns of \\(A\\), and each column has \\(m\\) entries. So the result has \\(m\\) entries no matter how large \\(n\\) is."
  },
  {
    "id": "1.4-prod-04",
    "section": "1.4",
    "topic": "The product Ax",
    "concept": "matrix-vector-product",
    "statement": "\\(Ax\\) is a linear combination of the rows of \\(A\\).",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Rows and columns play interchangeable roles in \\(Ax\\).",
    "explanation": "\\(Ax\\) combines the columns of \\(A\\). Rows enter only through the row-vector rule, which is a computational shortcut for the individual entries of the answer.",
    "why": {
      "prompt": "Why must it be the columns?",
      "choices": [
        "There is one weight for each entry of \\(x\\), and \\(x\\) has one entry per column of \\(A\\).",
        "Rows of \\(A\\) are never vectors.",
        "The rows of \\(A\\) all have the same number of entries as \\(x\\) only when \\(A\\) is square.",
        "Combining rows would give an answer in \\(\\mathbb{R}^m\\), which is the wrong space."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.4-rowrule-01",
    "section": "1.4",
    "topic": "The product Ax",
    "concept": "row-vector-rule",
    "statement": "The \\(i\\)th entry of \\(Ax\\) is obtained by pairing the entries of row \\(i\\) of \\(A\\) with the entries of \\(x\\) and adding the products.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The row-vector rule is a different definition that might disagree with the column definition.",
    "explanation": "This is the row-vector rule. It is a consequence of the definition: taking the \\(i\\)th entry of \\(x_1a_1+\\cdots+x_na_n\\) gives exactly that sum of products."
  },
  {
    "id": "1.4-rowrule-02",
    "section": "1.4",
    "topic": "The product Ax",
    "concept": "row-vector-rule",
    "statement": "The row-vector rule and the definition of \\(Ax\\) as a linear combination of columns can give different answers.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Two different procedures must compute two different things.",
    "explanation": "They always agree. The row-vector rule is derived from the column definition by reading off one entry at a time, so it is a way of computing the same vector."
  },
  {
    "id": "1.4-mateq-01",
    "section": "1.4",
    "topic": "Matrix equations",
    "concept": "matrix-equation",
    "statement": "An equation of the form \\(Ax=b\\), where \\(A\\) is a matrix and \\(b\\) is a vector, is called a matrix equation.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Matrix equation is a loose phrase rather than a definition.",
    "explanation": "This is the standard terminology. The unknown \\(x\\) is a vector, and solving the equation means finding every vector \\(x\\) that satisfies it."
  },
  {
    "id": "1.4-mateq-02",
    "section": "1.4",
    "topic": "Matrix equations",
    "concept": "matrix-equation",
    "statement": "In the matrix equation \\(Ax=b\\), the unknown \\(x\\) is a scalar.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "A single letter standing for an unknown must denote a single number.",
    "explanation": "If \\(A\\) is \\(m\\times n\\), then \\(x\\) is a vector in \\(\\mathbb{R}^n\\). Its entries \\(x_1,\\dots,x_n\\) are the scalars, and they serve as the weights on the columns of \\(A\\)."
  },
  {
    "id": "1.4-equiv-01",
    "section": "1.4",
    "topic": "Matrix equations",
    "concept": "matrix-equation-equivalence",
    "statement": "If \\(A\\) has columns \\(a_1,\\dots,a_n\\), then \\(Ax=b\\), the vector equation \\(x_1a_1+\\cdots+x_na_n=b\\), and the system with augmented matrix \\(\\begin{bmatrix}a_1&\\cdots&a_n&b\\end{bmatrix}\\) all have the same solution set.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "These are three different problems that happen to look similar.",
    "explanation": "The first two say the same thing by the definition of \\(Ax\\), and the second and third say the same thing because equality of vectors is equality in each entry. So one row reduction settles all three.",
    "why": {
      "prompt": "What is the practical payoff of this theorem?",
      "choices": [
        "A question about matrices, vectors, or systems can be moved to whichever of the three settings is easiest, and row reduction answers all of them.",
        "It shows every matrix equation has a unique solution.",
        "It shows the three formulations have different solution sets that must be compared.",
        "It replaces row reduction with a faster method."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.4-equiv-02",
    "section": "1.4",
    "topic": "Matrix equations",
    "concept": "matrix-equation-equivalence",
    "statement": "The three formulations agree only when \\(A\\) has at least as many rows as columns.",
    "answer": false,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "The equivalence theorem carries a hidden restriction on the shape of \\(A\\).",
    "explanation": "No condition on the shape of \\(A\\) is needed. The theorem holds for every \\(m\\times n\\) matrix \\(A\\) and every \\(b\\) in \\(\\mathbb{R}^m\\), since it follows directly from the definition of \\(Ax\\) and from what equality of vectors means."
  },
  {
    "id": "1.4-equiv-03",
    "section": "1.4",
    "topic": "Matrix equations",
    "concept": "matrix-equation-equivalence",
    "statement": "Row reducing \\(\\begin{bmatrix}A&b\\end{bmatrix}\\) is a legitimate way to solve the matrix equation \\(Ax=b\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Matrix equations need a method that does not involve augmented matrices.",
    "explanation": "By the equivalence theorem, the solutions of \\(Ax=b\\) are exactly the solutions of the system with that augmented matrix, so the familiar row reduction applies unchanged."
  },
  {
    "id": "1.4-solv-01",
    "section": "1.4",
    "topic": "Existence of solutions",
    "concept": "solvability-columns",
    "statement": "\\(Ax=b\\) has a solution if and only if \\(b\\) is a linear combination of the columns of \\(A\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Solvability of \\(Ax=b\\) is unrelated to the columns of \\(A\\).",
    "explanation": "A solution \\(x\\) is precisely a list of weights making \\(x_1a_1+\\cdots+x_na_n\\) equal to \\(b\\). So solutions exist exactly when \\(b\\) lies in the span of the columns.",
    "why": {
      "prompt": "Restate the condition using span.",
      "choices": [
        "\\(Ax=b\\) is consistent exactly when \\(b\\) is in \\(\\operatorname{Span}\\{a_1,\\dots,a_n\\}\\).",
        "\\(Ax=b\\) is consistent exactly when \\(b\\) is one of the columns of \\(A\\).",
        "\\(Ax=b\\) is consistent exactly when \\(A\\) has no zero columns.",
        "\\(Ax=b\\) is consistent exactly when \\(b\\) is the zero vector."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.4-solv-02",
    "section": "1.4",
    "topic": "Existence of solutions",
    "concept": "solvability-columns",
    "statement": "If \\(Ax=b\\) has a solution, then \\(b\\) must be one of the columns of \\(A\\).",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Being in the span of the columns means being among the columns.",
    "explanation": "Being in the span is far weaker than being one of the columns. Any weighted combination counts.",
    "counterexample": "With \\(A=\\begin{bmatrix}1&0\\\\0&1\\end{bmatrix}\\) and \\(b=\\begin{bmatrix}5\\\\7\\end{bmatrix}\\), the equation is solvable but \\(b\\) is not a column of \\(A\\)."
  },
  {
    "id": "1.4-solv-03",
    "section": "1.4",
    "topic": "Existence of solutions",
    "concept": "solvability-columns",
    "statement": "If \\(b\\) is not in the span of the columns of \\(A\\), then \\(Ax=b\\) has infinitely many solutions.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Failure of a condition produces many solutions rather than none.",
    "explanation": "If \\(b\\) is outside the span of the columns, then no choice of weights produces \\(b\\), so the equation has no solution at all."
  },
  {
    "id": "1.4-spansrm-01",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "spans-rm",
    "statement": "A set of vectors in \\(\\mathbb{R}^m\\) spans \\(\\mathbb{R}^m\\) when every vector in \\(\\mathbb{R}^m\\) is a linear combination of them.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Spanning means the vectors are spread out or point in many directions.",
    "explanation": "Spanning \\(\\mathbb{R}^m\\) means the span is all of \\(\\mathbb{R}^m\\), so nothing in \\(\\mathbb{R}^m\\) is left out."
  },
  {
    "id": "1.4-spansrm-02",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "spans-rm",
    "statement": "Any three vectors in \\(\\mathbb{R}^3\\) span \\(\\mathbb{R}^3\\).",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Having as many vectors as dimensions is enough to span.",
    "explanation": "The count is not enough; the vectors must genuinely reach in three independent directions. Three vectors lying in a common plane through the origin span only that plane.",
    "counterexample": "Three copies of \\(\\begin{bmatrix}1\\\\0\\\\0\\end{bmatrix}\\) span only a line."
  },
  {
    "id": "1.4-spansrm-03",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "spans-rm",
    "statement": "If a set of vectors in \\(\\mathbb{R}^4\\) contains more than four vectors, then it must span \\(\\mathbb{R}^4\\).",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Enough vectors will eventually fill up the space.",
    "explanation": "Extra vectors contribute nothing if they repeat directions already present. A long list can still have a small span.",
    "counterexample": "Ten copies of \\(\\begin{bmatrix}1\\\\0\\\\0\\\\0\\end{bmatrix}\\) span only a line in \\(\\mathbb{R}^4\\)."
  },
  {
    "id": "1.4-spansrm-04",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "spans-rm",
    "statement": "Fewer than \\(m\\) vectors can never span \\(\\mathbb{R}^m\\).",
    "answer": true,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "A small number of well-chosen vectors might still span the whole space.",
    "explanation": "Arrange \\(p\\) vectors as the columns of an \\(m\\times p\\) matrix \\(A\\). Each pivot occupies its own column and its own row, so there are at most \\(p\\) pivots. If \\(p<m\\), some row has no pivot, and then the columns of \\(A\\) do not span \\(\\mathbb{R}^m\\).",
    "why": {
      "prompt": "Which condition fails?",
      "choices": [
        "\\(A\\) cannot have a pivot position in every row.",
        "\\(A\\) cannot have a pivot position in every column.",
        "\\(A\\) must have a free variable.",
        "\\(A\\) must be inconsistent."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.4-tfae-01",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "pivot-in-every-row",
    "statement": "If \\(A\\) is \\(m\\times n\\) and has a pivot position in every row, then \\(Ax=b\\) has a solution for every \\(b\\) in \\(\\mathbb{R}^m\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Pivots in every row control uniqueness rather than existence.",
    "explanation": "A pivot in every row leaves no room for a row of the form \\([0\\ \\cdots\\ 0\\mid b]\\) with \\(b\\ne0\\) after reduction, so the augmented column can never be a pivot column and the equation is always consistent.",
    "why": {
      "prompt": "Which equivalent statement is this?",
      "choices": [
        "The columns of \\(A\\) span \\(\\mathbb{R}^m\\).",
        "The columns of \\(A\\) span \\(\\mathbb{R}^n\\).",
        "\\(Ax=b\\) has a unique solution for each \\(b\\).",
        "\\(A\\) has no free variables."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.4-tfae-02",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "pivot-in-every-row",
    "statement": "The columns of \\(A\\) span \\(\\mathbb{R}^m\\) exactly when \\(A\\) has a pivot position in every column.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Row and column are interchangeable in the spanning criterion.",
    "explanation": "The criterion is a pivot in every row, not every column. Pivots in every column concern free variables and uniqueness, which is a different question.",
    "counterexample": "\\(A=\\begin{bmatrix}1&0&0\\\\0&1&0\\end{bmatrix}\\) has columns spanning \\(\\mathbb{R}^2\\), yet its third column has no pivot.",
    "why": {
      "prompt": "Which quantity does a pivot in every row control?",
      "choices": [
        "Existence: whether \\(Ax=b\\) is solvable for every \\(b\\).",
        "Uniqueness: whether a solution is the only one.",
        "Whether \\(A\\) is square.",
        "Whether the columns of \\(A\\) are nonzero."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.4-tfae-03",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "pivot-in-every-row",
    "statement": "If \\(Ax=b\\) is consistent for some particular \\(b\\) in \\(\\mathbb{R}^m\\), then the columns of \\(A\\) span \\(\\mathbb{R}^m\\).",
    "answer": false,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "One solvable case is enough to establish the theorem's for every \\(b\\) condition.",
    "explanation": "The theorem requires solvability for every \\(b\\) in \\(\\mathbb{R}^m\\). A single \\(b\\) that happens to lie in the span of the columns says nothing about the rest of \\(\\mathbb{R}^m\\).",
    "counterexample": "\\(A=\\begin{bmatrix}1&1\\\\0&0\\end{bmatrix}\\) with \\(b=\\begin{bmatrix}1\\\\0\\end{bmatrix}\\) is consistent, but the columns of \\(A\\) span only a line in \\(\\mathbb{R}^2\\).",
    "why": {
      "prompt": "What kind of error is this?",
      "choices": [
        "A quantifier error: the theorem needs solvability for every \\(b\\), not for some \\(b\\).",
        "A hypothesis error: \\(A\\) must also be square.",
        "An arithmetic error in computing \\(Ax\\).",
        "A terminology error: consistent should read inconsistent."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.4-tfae-04",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "pivot-in-every-row",
    "statement": "If \\(A\\) is \\(3\\times5\\) and the columns of \\(A\\) span \\(\\mathbb{R}^3\\), then \\(A\\) has exactly three pivot positions.",
    "answer": true,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "A matrix with five columns should have five pivots.",
    "explanation": "Spanning \\(\\mathbb{R}^3\\) means a pivot in every row, and \\(A\\) has three rows. Since each pivot occupies its own row, there are exactly three. The remaining two columns are not pivot columns, so the system has free variables."
  },
  {
    "id": "1.4-tfae-05",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "pivot-in-every-row",
    "statement": "The columns of a \\(4\\times3\\) matrix can span \\(\\mathbb{R}^4\\).",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Three vectors could still reach every vector in \\(\\mathbb{R}^4\\).",
    "explanation": "Each pivot occupies its own column, so a matrix with three columns has at most three pivots. With four rows, some row has no pivot, and the columns therefore fail to span \\(\\mathbb{R}^4\\)."
  },
  {
    "id": "1.4-linear-01",
    "section": "1.4",
    "topic": "Properties of Ax",
    "concept": "matrix-vector-linearity",
    "statement": "If \\(A\\) is \\(m\\times n\\) and \\(u,v\\) are in \\(\\mathbb{R}^n\\), then \\(A(u+v)=Au+Av\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The product \\(Ax\\) has no useful algebraic rules.",
    "explanation": "The matrix-vector product distributes over vector addition. This follows from the definition together with the algebraic properties of vectors in \\(\\mathbb{R}^n\\)."
  },
  {
    "id": "1.4-linear-02",
    "section": "1.4",
    "topic": "Properties of Ax",
    "concept": "matrix-vector-linearity",
    "statement": "The identity \\(A(u+v)=Au+Av\\) requires \\(A\\) to be square.",
    "answer": false,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "Algebraic identities for \\(Ax\\) carry a hidden squareness assumption.",
    "explanation": "The identity holds for every \\(m\\times n\\) matrix \\(A\\). The only requirement is that \\(u\\) and \\(v\\) lie in \\(\\mathbb{R}^n\\), so that both products are defined."
  },
  {
    "id": "1.4-linear-03",
    "section": "1.4",
    "topic": "Properties of Ax",
    "concept": "matrix-vector-linearity",
    "statement": "If \\(A\\) is \\(m\\times n\\) and \\(u,v\\) are in \\(\\mathbb{R}^n\\), then \\(A(3u-2v)=3Au-2Av\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The two properties of \\(Ax\\) cannot be combined in one computation.",
    "explanation": "Distributing over the sum gives \\(A(3u)+A(-2v)\\), and pulling out the scalars gives \\(3Au-2Av\\). The two properties are normally used together like this."
  },
  {
    "id": "1.4-prod-05",
    "section": "1.4",
    "topic": "The product Ax",
    "concept": "matrix-vector-product",
    "statement": "If \\(A\\) is \\(3\\times5\\), then \\(Ax\\) is defined for \\(x\\) in \\(\\mathbb{R}^3\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The number of entries of \\(x\\) should match the number of rows of \\(A\\).",
    "explanation": "The entries of \\(x\\) are the weights on the columns of \\(A\\), and \\(A\\) has five columns. So \\(Ax\\) is defined for \\(x\\) in \\(\\mathbb{R}^5\\), and the result lies in \\(\\mathbb{R}^3\\)."
  },
  {
    "id": "1.4-prod-06",
    "section": "1.4",
    "topic": "The product Ax",
    "concept": "matrix-vector-product",
    "statement": "If \\(e_1\\) in \\(\\mathbb{R}^n\\) has first entry \\(1\\) and all other entries \\(0\\), then \\(Ae_1\\) is the first column of \\(A\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Multiplying by a vector of mostly zeros produces the zero vector.",
    "explanation": "The weights are \\(1,0,\\dots,0\\), so the combination is \\(1a_1+0a_2+\\cdots+0a_n=a_1\\). Multiplying by \\(e_i\\) selects the \\(i\\)th column."
  },
  {
    "id": "1.4-mateq-03",
    "section": "1.4",
    "topic": "Matrix equations",
    "concept": "matrix-equation",
    "statement": "In the equation \\(Ax=b\\), the vectors \\(x\\) and \\(b\\) always have the same number of entries.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Both sides of an equation must live in the same space, so \\(x\\) and \\(b\\) must match.",
    "explanation": "If \\(A\\) is \\(m\\times n\\), then \\(x\\) is in \\(\\mathbb{R}^n\\) while \\(b\\) is in \\(\\mathbb{R}^m\\). The two sides that must match are \\(Ax\\) and \\(b\\), both of which lie in \\(\\mathbb{R}^m\\). The sizes agree only when \\(m=n\\)."
  },
  {
    "id": "1.4-solv-04",
    "section": "1.4",
    "topic": "Existence of solutions",
    "concept": "solvability-columns",
    "statement": "If \\(Ax=b\\) has no solution, then \\(b\\) is a linear combination of the columns of \\(A\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Reversing a criterion without reversing its conclusion.",
    "explanation": "It is the other way around. Having no solution means precisely that no choice of weights produces \\(b\\), so \\(b\\) is not a linear combination of the columns."
  },
  {
    "id": "1.4-solv-05",
    "section": "1.4",
    "topic": "Existence of solutions",
    "concept": "solvability-columns",
    "statement": "For every matrix \\(A\\), the equation \\(Ax=0\\), where \\(0\\) is the zero vector, has at least one solution.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Solvability of \\(Ax=b\\) always depends on the particular \\(A\\).",
    "explanation": "Taking \\(x\\) to be the zero vector gives a combination of the columns with all weights \\(0\\), which is the zero vector. So this equation is consistent no matter what \\(A\\) is."
  },
  {
    "id": "1.4-spansrm-05",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "spans-rm",
    "statement": "Saying that a set of vectors spans \\(\\mathbb{R}^m\\) means that every vector in \\(\\mathbb{R}^m\\) is one of the vectors in the set.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Spanning means literally containing everything.",
    "explanation": "Spanning asks that every vector in \\(\\mathbb{R}^m\\) be reachable as a linear combination of the set, not that it already belong to the set. A finite set can span \\(\\mathbb{R}^m\\) even though \\(\\mathbb{R}^m\\) is infinite."
  },
  {
    "id": "1.4-tfae-06",
    "section": "1.4",
    "topic": "Spanning sets",
    "concept": "pivot-in-every-row",
    "statement": "If the columns of \\(A\\) span \\(\\mathbb{R}^m\\), then \\(Ax=b\\) is consistent for every \\(b\\) in \\(\\mathbb{R}^m\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Spanning is about the columns only and says nothing about solving equations.",
    "explanation": "Spanning means every \\(b\\) in \\(\\mathbb{R}^m\\) is a linear combination of the columns, and such a combination is exactly a solution of \\(Ax=b\\). These are two of the equivalent conditions in the theorem."
  }
];
