window.QUESTION_BANK = [
  {
    "id": "1.1-linear-01",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\(3x_1-\\sqrt{2}x_2+7=0\\) is a linear equation in \\(x_1,x_2\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A constant term on the left makes an equation nonlinear.",
    "explanation": "Rewrite it as \\(3x_1-\\sqrt{2}x_2=-7\\). The variables occur only to the first power and are multiplied by constant coefficients.",
    "why": {
      "prompt": "Why is the statement true?",
      "choices": [
        "Because every equation involving two variables is linear.",
        "Because it can be rewritten as \\(a_1x_1+a_2x_2=b\\) with constant coefficients.",
        "Because the number \\(7\\) is positive.",
        "Because a linear equation must have \\(b=0\\)."
      ],
      "correct": 1
    }
  },
  {
    "id": "1.1-linear-02",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\(x_1x_2+x_3=4\\) is a linear equation in \\(x_1,x_2,x_3\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Any equation made from variables and constants is linear.",
    "explanation": "The product \\(x_1x_2\\) prevents the equation from having the form \\(a_1x_1+\\cdots+a_nx_n=b\\).",
    "counterexample": "The obstruction is the product of variables, not the presence of \\(x_3\\)."
  },
  {
    "id": "1.1-linear-03",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\(x_1^2-5x_2=1\\) is a linear equation in \\(x_1,x_2\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Polynomial equations are automatically linear equations.",
    "explanation": "The term \\(x_1^2\\) is nonlinear. In a linear equation each variable appears only to the first power and is multiplied by a scalar coefficient."
  },
  {
    "id": "1.1-linear-04",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\(0x_1+0x_2=5\\) still has the form of a linear equation, even though it has no solution.",
    "answer": true,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "An equation must have a solution in order to count as linear.",
    "explanation": "The coefficients are allowed to be zero. This equation is simply \\(0=5\\), so it is linear in form but inconsistent as a one-equation system."
  },
  {
    "id": "1.1-linear-05",
    "section": "1.1",
    "topic": "Linear equations",
    "concept": "linear-equation",
    "statement": "\\((1+i)z_1-2z_2=i\\) is a linear equation when complex coefficients and variables are allowed.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Linear equations must have real coefficients.",
    "explanation": "The coefficients and right-hand side may be complex scalars. The variables still occur linearly."
  },
  {
    "id": "1.1-system-01",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution",
    "statement": "A solution of a linear system must satisfy every equation in the system simultaneously.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Satisfying any one equation is enough to solve a system.",
    "explanation": "A solution of a system is a choice of values for all variables that makes every equation in the system true."
  },
  {
    "id": "1.1-system-02",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution-set",
    "statement": "The solution set of a system is the collection of all assignments of values to the variables that solve the system.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The solution set is the collection of equations in the system.",
    "explanation": "The equations define the conditions. The solution set consists of the vectors or tuples satisfying all of those conditions."
  },
  {
    "id": "1.1-system-03",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "equivalent-systems",
    "statement": "Two linear systems can look different and still be equivalent.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Equivalent systems must contain the same equations.",
    "explanation": "Equivalence is about having the same solution set, not about having identical equations."
  },
  {
    "id": "1.1-system-04",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "equivalent-systems",
    "statement": "If two systems have the same coefficient matrix, then they are equivalent.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The coefficient matrix alone determines the solution set.",
    "explanation": "The right-hand side matters. For example, \\(x=0\\) and \\(x=1\\) have the same coefficient matrix \\([1]\\) but different solution sets.",
    "counterexample": "\\(x=0\\) versus \\(x=1\\)."
  },
  {
    "id": "1.1-system-05",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "solution-count",
    "statement": "A linear system over the real or complex numbers can have exactly two distinct solutions.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Linear systems can have any finite number of solutions.",
    "explanation": "If \\(u\\) and \\(v\\) are two distinct solutions of \\(Ax=b\\), then \\(tu+(1-t)v\\) is also a solution for every scalar \\(t\\). Thus two distinct solutions force infinitely many.",
    "why": {
      "prompt": "Which idea best explains why?",
      "choices": [
        "Two distinct solutions generate infinitely many solutions along the affine line joining them.",
        "Every consistent system has a pivot in every column.",
        "Every linear system has at least three equations.",
        "A system with two solutions must have two free variables."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.1-system-06",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "consistency",
    "statement": "A consistent linear system must have exactly one solution.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Consistent means uniquely solvable.",
    "explanation": "Consistent means only that at least one solution exists. A consistent system may have one solution or infinitely many solutions."
  },
  {
    "id": "1.1-system-07",
    "section": "1.1",
    "topic": "Linear systems",
    "concept": "consistency",
    "statement": "An inconsistent system has an empty solution set.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Inconsistent means the equations are merely inconvenient or redundant.",
    "explanation": "By definition, an inconsistent system has no solution, so its solution set is empty."
  },
  {
    "id": "1.1-matrix-01",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "coefficient-matrix",
    "statement": "The coefficient matrix of a system includes the constants on the right-hand side of the equations.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Coefficient matrix and augmented matrix are the same object.",
    "explanation": "The coefficient matrix contains only the coefficients of the variables. Appending the right-hand-side column produces the augmented matrix.",
    "why": {
      "prompt": "Which distinction is correct?",
      "choices": [
        "The augmented matrix omits the right-hand side.",
        "The coefficient matrix omits the right-hand side; the augmented matrix includes it.",
        "Both matrices must be square.",
        "The coefficient matrix always has one more column."
      ],
      "correct": 1
    }
  },
  {
    "id": "1.1-matrix-02",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "augmented-matrix",
    "statement": "For a system of \\(m\\) equations in \\(n\\) variables, its coefficient matrix is \\(m\\times n\\), while its augmented matrix has \\(m\\) rows and \\(n+1\\) columns.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Rows count variables and columns count equations.",
    "explanation": "There is one row per equation and one coefficient column per variable. The augmented matrix adds one right-hand-side column."
  },
  {
    "id": "1.1-matrix-03",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "matrix-dimensions",
    "statement": "An \\(m\\times n\\) matrix has \\(m\\) rows and \\(n\\) columns.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The order in matrix dimensions is columns by rows.",
    "explanation": "Matrix dimensions are always listed as rows by columns."
  },
  {
    "id": "1.1-matrix-04",
    "section": "1.1",
    "topic": "Matrices and systems",
    "concept": "matrix-vs-system",
    "statement": "An abstract matrix, with no system attached to it, is itself either consistent or inconsistent.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Terminology for systems automatically applies to matrices.",
    "explanation": "Consistency is a property of a system of equations. A matrix may represent an augmented matrix of a system, but an abstract matrix by itself is not a system.",
    "counterexample": "The same array of numbers can be studied simply as a matrix without assigning any right-hand-side column."
  },
  {
    "id": "1.1-rowops-01",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-scaling",
    "statement": "Multiplying a row by \\(0\\) is an elementary row operation.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A row may be scaled by any scalar.",
    "explanation": "Row scaling must use a nonzero scalar. Multiplying by zero destroys information and cannot be undone."
  },
  {
    "id": "1.1-rowops-02",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-replacement",
    "statement": "Adding a multiple of one row to a different row is an elementary row operation.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Row replacement means replacing a row by an arbitrary new row.",
    "explanation": "This is the row-replacement operation: replace one row by itself plus a scalar multiple of another row."
  },
  {
    "id": "1.1-rowops-03",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-interchange",
    "statement": "Interchanging two equations in a system changes its solution set.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Changing the order of equations changes the system's solutions.",
    "explanation": "The order in which the equations are listed does not affect which values satisfy all of them."
  },
  {
    "id": "1.1-rowops-04",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-equivalence",
    "statement": "If the augmented matrices of two systems are row equivalent, then the systems are equivalent.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Row operations can change the solution set.",
    "explanation": "Each elementary row operation replaces a system by one with the same solutions, so a sequence of such operations preserves the solution set.",
    "why": {
      "prompt": "What is the key reason?",
      "choices": [
        "Every elementary row operation is reversible and preserves the solution set.",
        "Every row-equivalent matrix is square.",
        "Row-equivalent matrices have identical entries.",
        "Equivalent systems must have the same equations in the same order."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.1-rowops-05",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-equivalence",
    "statement": "Row-equivalent matrices must have the same dimensions.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Row operations may add or remove rows or columns.",
    "explanation": "Elementary row operations change entries or row order, but they do not change the number of rows or columns."
  },
  {
    "id": "1.1-rowops-06",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "row-equivalence",
    "statement": "If \\(A\\) is row equivalent to \\(B\\), then \\(B\\) is row equivalent to \\(A\\).",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Row equivalence only goes in the direction in which the operations were performed.",
    "explanation": "Every elementary row operation has an inverse elementary row operation, so the sequence can be reversed."
  },
  {
    "id": "1.1-rowops-07",
    "section": "1.1",
    "topic": "Elementary row operations",
    "concept": "equivalent-systems",
    "statement": "If two systems are equivalent, then their augmented matrices must be row equivalent.",
    "answer": false,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "The implication between row equivalence and equivalent systems automatically works both ways.",
    "explanation": "Row-equivalent augmented matrices always give equivalent systems, but the converse can fail. In particular, all inconsistent systems have the same empty solution set, while their augmented matrices need not have the same RREF.",
    "counterexample": "The systems \\(x=0,\\;0=1\\) and \\(y=0,\\;0=1\\) (in variables \\(x,y\\)) are both inconsistent, hence equivalent as systems, but their augmented matrices have different RREFs."
  },
  {
    "id": "1.2-ref-01",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref",
    "statement": "In row echelon form, every leading entry must equal \\(1\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "REF and RREF have the same requirements.",
    "explanation": "A leading entry in REF only needs to be nonzero. Requiring each leading entry to be \\(1\\) is part of reduced echelon form."
  },
  {
    "id": "1.2-ref-02",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref",
    "statement": "A matrix can be in row echelon form with a zero row above a nonzero row.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The location of zero rows does not matter in echelon form.",
    "explanation": "In echelon form, every nonzero row must occur above every zero row."
  },
  {
    "id": "1.2-ref-03",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref",
    "statement": "As you move down the nonzero rows of a matrix in echelon form, the leading entries move strictly to the right.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Leading entries may occur in the same column in different nonzero rows.",
    "explanation": "Each leading entry in a lower nonzero row must be to the right of the leading entry in the row above."
  },
  {
    "id": "1.2-ref-04",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref",
    "statement": "In row echelon form, every entry below a leading entry is zero.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Zeros below pivots are required only in RREF.",
    "explanation": "Zeros below each leading entry are already required in echelon form."
  },
  {
    "id": "1.2-ref-05",
    "section": "1.2",
    "topic": "Echelon form",
    "concept": "ref-vs-rref",
    "statement": "In row echelon form, every entry above a leading entry must be zero.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "REF already has zeros both above and below pivots.",
    "explanation": "Zeros above pivot locations are required for reduced echelon form, not ordinary echelon form."
  },
  {
    "id": "1.2-rref-01",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "rref",
    "statement": "In reduced row echelon form, a leading entry may be any nonzero scalar; it does not have to equal \\(1\\).",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "REF and RREF place the same requirements on leading entries.",
    "explanation": "RREF requires each leading entry of a nonzero row to be \\(1\\). Ordinary REF allows other nonzero leading entries."
  },
  {
    "id": "1.2-rref-02",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "rref",
    "statement": "In reduced row echelon form, a leading \\(1\\) is the only nonzero entry in its column.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Only the entries below a leading 1 need to vanish in RREF.",
    "explanation": "RREF requires zeros both below and above each leading \\(1\\)."
  },
  {
    "id": "1.2-rref-03",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "unique-rref",
    "statement": "Every matrix is row equivalent to exactly one matrix in row echelon form.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "The uniqueness theorem applies to REF rather than RREF.",
    "explanation": "A matrix can have many echelon forms. What is unique is its reduced row echelon form.",
    "counterexample": "Both \\(\\begin{bmatrix}1&2\\\\0&1\\end{bmatrix}\\) and \\(\\begin{bmatrix}1&0\\\\0&1\\end{bmatrix}\\) are echelon matrices and are row equivalent."
  },
  {
    "id": "1.2-rref-04",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "unique-rref",
    "statement": "Every matrix is row equivalent to a unique reduced row echelon form.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Different row-reduction choices can produce different RREFs.",
    "explanation": "Although the sequence of row operations is not unique, the final RREF is unique."
  },
  {
    "id": "1.2-rref-05",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "row-equivalence",
    "statement": "If two matrices are row equivalent, then they have the same reduced row echelon form.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Row-equivalent matrices can have unrelated canonical forms.",
    "explanation": "Row-equivalent matrices lie in the same row-equivalence class, and each class has one unique RREF."
  },
  {
    "id": "1.2-rref-06",
    "section": "1.2",
    "topic": "Reduced echelon form",
    "concept": "row-equivalence",
    "statement": "If two matrices have the same reduced row echelon form, then they are row equivalent.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Sharing an RREF is weaker than row equivalence.",
    "explanation": "Each matrix is row equivalent to that common RREF, so reversing one sequence and composing the operations shows the two matrices are row equivalent."
  },
  {
    "id": "1.2-pivot-01",
    "section": "1.2",
    "topic": "Pivot positions",
    "concept": "pivot-position",
    "statement": "A pivot position of \\(A\\) is determined by where a leading \\(1\\) occurs in the RREF of \\(A\\).",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A pivot position is any location containing a nonzero entry in the original matrix.",
    "explanation": "Pivot positions are locations in the original matrix corresponding to leading \\(1\\)s in its unique RREF."
  },
  {
    "id": "1.2-pivot-02",
    "section": "1.2",
    "topic": "Pivot positions",
    "concept": "pivot-column",
    "statement": "Every nonzero column of a matrix is a pivot column.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A nonzero column automatically contains a pivot position.",
    "explanation": "A nonzero column may fail to contain a pivot position. Pivot columns are determined by the locations of leading \\(1\\)s in the RREF."
  },
  {
    "id": "1.2-pivot-03",
    "section": "1.2",
    "topic": "Pivot positions",
    "concept": "pivot-position",
    "statement": "The pivot positions of a matrix can depend on which legal sequence of row operations you choose.",
    "answer": false,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Because row-reduction paths differ, pivot locations can differ.",
    "explanation": "The RREF is unique, so the locations of its leading \\(1\\)s—and therefore the pivot positions—are fixed."
  },
  {
    "id": "1.2-gauss-01",
    "section": "1.2",
    "topic": "Gaussian elimination",
    "concept": "gaussian-elimination",
    "statement": "Gaussian elimination uses elementary row operations to produce an echelon form of a matrix.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Gaussian elimination requires going all the way to RREF.",
    "explanation": "The forward phase of Gaussian elimination produces an echelon form. Further reduction can be used when RREF is desired."
  },
  {
    "id": "1.2-variables-01",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "basic-variable",
    "statement": "In a linear system, a basic variable corresponds to a pivot column of the coefficient matrix.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A pivot in the augmented column represents a basic variable.",
    "explanation": "Variables correspond to columns of the coefficient matrix. A variable is basic when its coefficient column is a pivot column."
  },
  {
    "id": "1.2-variables-02",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "free-variable",
    "statement": "Every variable whose coefficient column contains at least one nonzero entry is a basic variable.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Any nonzero coefficient column must be a pivot column.",
    "explanation": "A variable is basic only when its coefficient column is a pivot column. A nonpivot column can contain nonzero entries; its variable is free."
  },
  {
    "id": "1.2-variables-03",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "free-variable",
    "statement": "In a consistent system, once values are chosen for all free variables, the values of the basic variables are uniquely determined.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Choosing free variables may still leave basic variables undetermined.",
    "explanation": "After row reduction, each basic variable is expressed in terms of the free variables. Fixing all free-variable values therefore fixes every basic variable.",
    "why": {
      "prompt": "What does 'free' mean here?",
      "choices": [
        "A free variable can be assigned a value, after which the basic variables are determined.",
        "A free variable never appears in any equation.",
        "A free variable must equal zero.",
        "A free variable corresponds to a pivot column."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-variables-04",
    "section": "1.2",
    "topic": "Basic and free variables",
    "concept": "basic-variable",
    "statement": "The number of basic variables equals the number of pivot columns in the coefficient matrix.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "The augmented column can add a basic variable.",
    "explanation": "There is one variable for each coefficient column, and exactly the variables in pivot columns are basic."
  },
  {
    "id": "1.2-existence-01",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "consistency-test",
    "statement": "A system is inconsistent exactly when the rightmost column of its augmented matrix is a pivot column.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "A pivot in the augmented column is harmless.",
    "explanation": "A pivot in the augmented column produces an echelon row of the form \\([0\\ \\cdots\\ 0\\mid b]\\) with \\(b\\ne0\\), which represents an impossible equation \\(0=b\\).",
    "why": {
      "prompt": "Which row signals the problem?",
      "choices": [
        "\\([0\\ \\cdots\\ 0\\mid b]\\) with \\(b\\ne0\\)",
        "\\([0\\ \\cdots\\ 0\\mid 0]\\)",
        "Any row containing a zero",
        "Any row whose first entry is not \\(1\\)"
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-existence-02",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "consistency-test",
    "statement": "An echelon row \\([0\\ 0\\ 0\\mid 5]\\) can be ignored when deciding whether the corresponding system is consistent.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A row with no variable terms never affects the solution set.",
    "explanation": "That row represents \\(0=5\\), which is impossible, so it proves the system is inconsistent."
  },
  {
    "id": "1.2-existence-03",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "consistency-test",
    "statement": "An echelon row \\([0\\ 0\\ 0\\mid 0]\\) proves that the corresponding system is inconsistent.",
    "answer": false,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Any zero row indicates inconsistency.",
    "explanation": "That row represents \\(0=0\\), which imposes no additional restriction and causes no inconsistency."
  },
  {
    "id": "1.2-existence-04",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "unique-solution",
    "statement": "If a system is consistent and has no free variables, then it has a unique solution.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "A consistent system without free variables might still have many solutions.",
    "explanation": "With no free variables, every variable is basic and is uniquely determined."
  },
  {
    "id": "1.2-existence-05",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "infinite-solutions",
    "statement": "If a system is consistent and has at least one free variable, then it has infinitely many solutions.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "One free variable gives only a few extra solutions.",
    "explanation": "A free variable may take infinitely many scalar values over the real or complex numbers, and each choice determines a solution."
  },
  {
    "id": "1.2-existence-06",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "unique-solution",
    "statement": "If a system has no free variables, then it must have a unique solution.",
    "answer": false,
    "difficulty": 2,
    "variant": "hypothesis",
    "misconception": "The consistency hypothesis in the existence-and-uniqueness theorem can be omitted.",
    "explanation": "The system could be inconsistent because the augmented column is a pivot column. 'No free variables' controls uniqueness only after existence is known.",
    "counterexample": "\\(x=0\\) together with \\(0=1\\) has no free variable \\(x\\), but it has no solution."
  },
  {
    "id": "1.2-existence-07",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "unique-solution",
    "statement": "A pivot in every coefficient column guarantees that a system has a unique solution.",
    "answer": false,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "Pivots in all variable columns guarantee both existence and uniqueness.",
    "explanation": "Pivots in all coefficient columns mean there are no free variables, but the system may still be inconsistent if the augmented column is also a pivot column.",
    "counterexample": "\\(x=0,\\;y=0,\\;0=1\\) has pivots in both coefficient columns and is inconsistent."
  },
  {
    "id": "1.2-existence-08",
    "section": "1.2",
    "topic": "Existence and uniqueness",
    "concept": "consistency-test",
    "statement": "If the rightmost column of an augmented matrix is not a pivot column, then the corresponding system is consistent.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Consistency requires a pivot in every row or every coefficient column.",
    "explanation": "The absence of a pivot in the augmented column means row reduction never produces an impossible equation \\(0=b\\) with \\(b\\ne0\\)."
  },
  {
    "id": "1.2-parametric-01",
    "section": "1.2",
    "topic": "Parametric solution sets",
    "concept": "parametric-form",
    "statement": "For a consistent system, RREF makes it possible to express each basic variable in terms of the free variables.",
    "answer": true,
    "difficulty": 1,
    "variant": "core",
    "misconception": "Free variables must be solved in terms of basic variables.",
    "explanation": "The usual parametric description treats the free variables as parameters and solves the pivot equations for the basic variables."
  },
  {
    "id": "1.2-parametric-02",
    "section": "1.2",
    "topic": "Parametric solution sets",
    "concept": "ref-suffices",
    "statement": "If your only goal is to decide whether a system is consistent, reaching row echelon form is enough; continuing to RREF is unnecessary.",
    "answer": true,
    "difficulty": 2,
    "variant": "core",
    "misconception": "Every row-reduction problem must continue to RREF.",
    "explanation": "In REF you can already see whether an impossible row \\([0\\ \\cdots\\ 0\\mid b]\\), \\(b\\ne0\\), occurs. RREF is useful for reading an explicit solution description more directly.",
    "why": {
      "prompt": "Why does REF suffice for existence?",
      "choices": [
        "The inconsistency row is already visible in echelon form.",
        "Every echelon matrix is already reduced.",
        "Free variables disappear in echelon form.",
        "RREF can change whether solutions exist."
      ],
      "correct": 0
    }
  },
  {
    "id": "1.2-parametric-03",
    "section": "1.2",
    "topic": "Parametric solution sets",
    "concept": "parametric-form",
    "statement": "It is mathematically impossible to obtain a parametric description of a solution set from REF without first computing RREF.",
    "answer": false,
    "difficulty": 3,
    "variant": "hypothesis",
    "misconception": "RREF is logically necessary rather than a convenient canonical form.",
    "explanation": "RREF makes the parametric form easy to read off, but REF together with back-substitution can also produce a parametric description. In this course, reducing to RREF is often the cleanest standard procedure."
  }
];
